# These are supported funding model platforms

github: [your-github-username]
patreon: [your-patreon-username]
open_collective: [your-open-collective-username]
ko_fi: [your-ko-fi-username]
tidelift: [your-tidelift-project-name]
community_bridge: [your-community-bridge-project-name]
liberapay: [your-liberapay-username]
issuehunt: [your-issuehunt-username]
otech_gittip: [your-otech-gittip-username]
custom: ['https://www.example.com/donate']