name: Gemini Assistant

on:
  issue_comment:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  assist:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      discussions: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Gemini CLI Assistant
        uses: google-github-actions/run-gemini-cli@v0.1.11
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: "You are a helpful assistant. Respond to the user's comment."
        env:
          SURFACE: GitHub