name: hugging-face Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install torch transformers

      - name: Run PR Review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git diff origin/main...HEAD > changes.diff

          python - <<'EOF'
          from transformers import pipeline

          # pick a lightweight model
          reviewer = pipeline("text-generation", model="google/flan-t5-base")

          with open("changes.diff") as f:
              diff = f.read()

          prompt = f"Review the following code diff and provide feedback:\n{diff}"
          out = reviewer(prompt, max_length=512, do_sample=False)
          print("AI Review:\n", out[0]["generated_text"])
          EOF
