name: HuggingFace Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install torch transformers

      - name: Generate and Post AI Review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git diff origin/main...HEAD > changes.diff

          echo "### 🤖 AI Code Review" > review.md
          python - <<'EOF' >> review.md
          from transformers import pipeline

          # use correct pipeline for flan-t5-base
          reviewer = pipeline("text2text-generation", model="google/flan-t5-base")

          with open("changes.diff") as f:
            diff = f.read()

          prompt = f"Review the following code diff and provide constructive feedback:\n{diff}"
          out = reviewer(prompt, max_length=512, do_sample=False)
          print(out[0]["generated_text"])
          EOF

          gh pr comment ${{ github.event.pull_request.number }} --body-file review.md
